---
title: "Presentations"
format: qmdrslides-revealjs
---

## Anatomy of a Document

Presentations, like any Quarto document, 

1. YAML [`format: revealjs`]{.fragment}
2. Markdown
3. Code cells


## Our Turn {#toc .our-turn}

This slide deck is in desperate need of some help. Let's...

1. [Add some organization](#org)
2. [Reveal on click](#click)
3. [Split content into columns](#cols)
4. [Deal with code more deftly](#code)
5. Add logo and footer
6. Enable slide annotation

## Your Turn {.your-turn style="font-size: .8em"}

Pick up where we left off and modify then YAML to...

1. Change the [transition style](https://quarto.org/docs/presentations/revealjs/advanced.html#slide-transitions) between slides
2. Change the [slide size](https://quarto.org/docs/presentations/revealjs/advanced.html#presentation-size)
3. Add [slide numbers](https://quarto.org/docs/presentations/revealjs/presenting.html#slide-numbers)
4. Experiment with different [slide background options](https://quarto.org/docs/presentations/revealjs/#slide-backgrounds)

```{r}
library(countdown)
countdown::countdown(10)
```



## Our Turn {.our-turn}

This slide deck is in desperate need of some help. Let's...

1. Add a timer
2. Print to PDF
3. Prepare to present
4. Add a theme

## SCSS

```css {code-line-numbers="1|3-4|6-7|9-11|13-16"}
/*-- scss:defaults --*/

// fonts
$font-family-sans-serif: "Palatino Linotype", serif !default;

// colors
$body-bg: #f0f1eb !default;

// headings
$presentation-heading-font: "Palatino Linotype", serif !default;
$presentation-heading-color: #383d3d !default;

/*-- scss:rules --*/

blockquote {
  margin-left: 80px !important;
}
```

## Your Turn {.your-turn style="font-size: .8em"}

It's time to make this presentation really shine. Use SASS variables to

1. Select a new [theme](https://quarto.org/docs/presentations/revealjs/themes.html#using-themes) to use.
2. Personalize your theme by
   a. Changing the background color
   b. Changing the font size.

# Appendix

## Add some organization {#org}

1. Add title slides by starting a slide with `#` instead of `##` ([docs](https://quarto.org/docs/presentations/#creating-slides)).
2. Press "o" to see slide overview ([docs](https://quarto.org/docs/presentations/revealjs/presenting.html#overview-mode)).

:::{style="text-align: center"}
{{< fa arrow-rotate-left >}} Return to [Our Turn](#toc) {{< fa arrow-rotate-left >}}
:::

## Reveal on click {#click}

1. Add `. . .` on a new line to introduce a break in the slide that you can click to advance.
2. Can add the `.fragment` class to any div or span to reveal on click ([docs](https://quarto.org/docs/presentations/revealjs/advanced.html#fragments)).
3. Add `.incremental` class to a div outside a list to incrementally reveal list items ([docs](https://quarto.org/docs/presentations/revealjs/#incremental-lists)).
4. Can set `incremental: true` option in yaml under `format: revealjs`.
5. Can create an exception using `.nonincremental` class on a div.

:::{style="text-align: center"}
{{< fa arrow-rotate-left >}} Return to [Our Turn](#toc) {{< fa arrow-rotate-left >}}
:::

## Split content into columns {#cols}

Nest `.column` divs inside a `.columns` div and specify their width ([docs](https://quarto.org/docs/presentations/revealjs/#multiple-columns))

   ```markdown
   :::{.columns}
   
   :::{.column width="50%"}
   Here is the stuff on the left.
   :::
   
   :::{.column width="50%"}
   Here is the stuff on the right.
   :::
   
   :::
   ```

:::{style="text-align: center"}
{{< fa arrow-rotate-left >}} Return to [Our Turn](#toc) {{< fa arrow-rotate-left >}}
:::

## Deal with code more deftly {#code .smaller}

1. Naive way: put a code cell in left column with `eval: false` and a copy of it in the right column with `echo: false`.
2. Instead, try putting both of those code cells in a div with `.panel-tabset`. Precede each cell block with a level 2 header to serve as the label for each tab.
3. Better yet: remove the tabset and the columns. Add the code cell option.

   ```{{r}}
   #| output-location: column-fragment
   ```

   This will put it in the right column and appear after a click. Read the docs for other good options ([docs](https://quarto.org/docs/presentations/revealjs/index.html#output-location))
   
:::{style="text-align: center"}
{{< fa arrow-rotate-left >}} Return to [Our Turn](#toc) {{< fa arrow-rotate-left >}}
:::

